CREATE DATABASE GALACTICUSBD;
USE GALACTICUSBD;

-- TABLA SUCURSALES 
CREATE TABLE SUCURSALES (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    NOMBRE VARCHAR(50) NOT NULL,
    DIRECCION VARCHAR(250) NOT NULL,
    TELEFONO VARCHAR(20) NOT NULL,
    CORREO VARCHAR(50) NOT NULL,
    FECHA_CREACION DATETIME DEFAULT GETDATE(),
    ESTADO BIT DEFAULT 1
);

-- TABLA CATEGORIAS
CREATE TABLE CATEGORIAS (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    SUCURSAL_ID INT NOT NULL,
    NOMBRE VARCHAR(150) NOT NULL,
    FECHA_CREACION DATETIME DEFAULT GETDATE(),
    ESTADO BIT DEFAULT 1,
    CONSTRAINT FK_CATEGORIAS_SUCURSALES
    FOREIGN KEY (SUCURSAL_ID) REFERENCES SUCURSALES (ID)
);

-- TABLA PROVEEDORES
CREATE TABLE PROVEEDORES (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    SUCURSAL_ID INT NOT NULL,
    NOMBRE VARCHAR(150) NOT NULL,
    RUC VARCHAR(15) NOT NULL,
    TELEFONO VARCHAR(50) NOT NULL,
    DIRECCION VARCHAR(150) NOT NULL,
    CORREO VARCHAR(150) NOT NULL,
    FECHA_CREACION DATETIME DEFAULT GETDATE(),
    ESTADO BIT DEFAULT 1,
    CONSTRAINT FK_PROVEEDORES_SUCURSALES
    FOREIGN KEY (SUCURSAL_ID) REFERENCES SUCURSALES (ID)
);

-- TABLA MONEDAS
CREATE TABLE MONEDAS (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    SUCURSAL_ID INT NOT NULL,
    NOMBRE VARCHAR(50) NOT NULL,
    SIMBOLO VARCHAR(20),
    CODIGO_ISO VARCHAR(20),
    FECHA_CREACION DATETIME DEFAULT GETDATE(),
    ESTADO BIT DEFAULT 1,
    CONSTRAINT FK_MONEDAS_SUCURSALES
    FOREIGN KEY (SUCURSAL_ID) REFERENCES SUCURSALES (ID)
);

-- TABLA PRODUCTOS
CREATE TABLE PRODUCTOS (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    SUCURSAL_ID INT NOT NULL,
    CATEGORIA_ID INT NOT NULL,
    NOMBRE VARCHAR(150) NOT NULL,
    DESCRIPCION VARCHAR(250) NOT NULL,
    STOCK INT,
    PROVEEDOR_ID INT NOT NULL,
    MONEDA_ID INT NOT NULL,
    PRECIO_VENTA NUMERIC(18, 2),
    PRODUCTO_IMG VARCHAR(MAX),
    FECHA_CREACION DATETIME DEFAULT GETDATE(),
    ESTADO BIT DEFAULT 1,
    CONSTRAINT FK_PRODUCTOS_SUCURSALES
    FOREIGN KEY (SUCURSAL_ID) REFERENCES SUCURSALES (ID),
    CONSTRAINT FK_PRODUCTOS_CATEGORIAS
    FOREIGN KEY (CATEGORIA_ID) REFERENCES CATEGORIAS (ID),
    CONSTRAINT FK_PRODUCTOS_PROVEEDORES
    FOREIGN KEY (PROVEEDOR_ID) REFERENCES PROVEEDORES (ID),
    CONSTRAINT FK_PRODUCTOS_MONEDAS
    FOREIGN KEY (MONEDA_ID) REFERENCES MONEDAS (ID)
);

-- TABLA DOCUMENTOS
CREATE TABLE DOCUMENTOS (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    NOMBRE VARCHAR(50),
    TIPO VARCHAR(150), 
    FECHA_CREACION DATETIME DEFAULT GETDATE(),
    ESTADO BIT DEFAULT 1
);

-- TABLA PAGOS
CREATE TABLE PAGOS (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    NOMBRE VARCHAR(150),
    FECHA_CREACION DATETIME DEFAULT GETDATE(),
    ESTADO BIT DEFAULT 1
);

-- TABLA ROLES
CREATE TABLE ROLES (
    ROL_ID INT IDENTITY(1,1) PRIMARY KEY,
    SUCURSAL_ID INT NOT NULL,
    NOMBRE VARCHAR(150),
    FECHA_CREACION DATETIME DEFAULT GETDATE(),
    ESTADO BIT DEFAULT 1,
    CONSTRAINT FK_ROLES_SUCURSALES
    FOREIGN KEY (SUCURSAL_ID) REFERENCES SUCURSALES (ID)
);

-- TABLA USUARIOS
CREATE TABLE USUARIOS (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    SUCURSAL_ID INT NOT NULL,
    CORREO VARCHAR(150) NOT NULL,
    NOMBRE VARCHAR(150),
    APELLIDO VARCHAR(150),
    DNI VARCHAR(50),
    TELEFONO VARCHAR(50),
    CONTRASENIA VARCHAR(50) NOT NULL,
    ROL_ID INT NOT NULL,
    IMAGEN VARCHAR(MAX),
    FECHA_CREACION DATETIME DEFAULT GETDATE(),
    EST INT,
    CONSTRAINT FK_USUARIOS_SUCURSALES
    FOREIGN KEY (SUCURSAL_ID) REFERENCES SUCURSALES (ID),
    CONSTRAINT FK_USUARIOS_ROLES
    FOREIGN KEY (ROL_ID) REFERENCES ROLES (ROL_ID)
);

-- TABLA COMPRAS
CREATE TABLE COMPRAS (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    SUCURSAL_ID INT NOT NULL,
    PAGO_ID INT NOT NULL,
    COMENTARIO VARCHAR(500),
    USUARIO_ID INT NOT NULL,
    MONEDA_ID INT NOT NULL,
    DOCUMENTO_ID INT NOT NULL,    
    FECHA_CREACION DATETIME DEFAULT GETDATE(),
    ESTADO BIT DEFAULT 1,
    CONSTRAINT FK_COMPRAS_SUCURSALES
    FOREIGN KEY (SUCURSAL_ID) REFERENCES SUCURSALES (ID),
    FOREIGN KEY (PAGO_ID) REFERENCES PAGOS (ID),
    FOREIGN KEY (USUARIO_ID) REFERENCES USUARIOS (ID),
    FOREIGN KEY (MONEDA_ID) REFERENCES MONEDAS (ID),
    FOREIGN KEY (DOCUMENTO_ID) REFERENCES DOCUMENTOS (ID)
);

-- TABLA COMPRADETALLES
CREATE TABLE COMPRADETALLES (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    COMPRA_ID INT NOT NULL,
    PRODUCTO_ID INT NOT NULL,
    PRODUCTO_PRECIO_COMPRA NUMERIC(18, 2) NOT NULL,
    CANTIDAD INT NOT NULL,
    FECHA_CREACION DATETIME DEFAULT GETDATE(),
    ESTADO BIT DEFAULT 1,
    CONSTRAINT FK_COMPRADETALLES_COMPRAS
    FOREIGN KEY (COMPRA_ID) REFERENCES COMPRAS (ID),
    CONSTRAINT FK_COMPRADETALLES_PRODUCTOS
    FOREIGN KEY (PRODUCTO_ID) REFERENCES PRODUCTOS (ID)
);

-- TABLA MENUS
CREATE TABLE MENUS (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    NOMBRE VARCHAR(150) NOT NULL,
    RUTA VARCHAR(250) NOT NULL,
    IDENTIFICADOR VARCHAR(150) NOT NULL,
    GRUPO VARCHAR(150) NOT NULL,
    ICONO VARCHAR(150) NOT NULL,
    FECHA_CREACION DATETIME DEFAULT GETDATE(),
    ESTADO BIT DEFAULT 1
);

-- TABLA MENUDETALLES
CREATE TABLE MENUDETALLES (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    MENU_ID INT NOT NULL,
    ROL_ID INT NOT NULL,
    PERMITIDO BIT DEFAULT 0,
    FECHA_CREACION DATETIME DEFAULT GETDATE(),
    ESTADO BIT DEFAULT 1,
    CONSTRAINT FK_MENUDETALLES_MENUS
    FOREIGN KEY (MENU_ID) REFERENCES MENUS (ID),
    CONSTRAINT FK_MENUDETALLES_ROLES
    FOREIGN KEY (ROL_ID) REFERENCES ROLES (ROL_ID)
);

-- TABLA CLIENTES
CREATE TABLE CLIENTES (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    SUCURSAL_ID INT NOT NULL,
    NOMBRE VARCHAR(150) NOT NULL,
    RUC VARCHAR(15),
    DNI VARCHAR(15),
    TELEFONO VARCHAR(50),
    DIRECCION VARCHAR(150),
    CORREO VARCHAR(150),
    FECHA_CREACION DATETIME DEFAULT GETDATE(),
    ESTADO BIT DEFAULT 1,
    CONSTRAINT FK_CLIENTES_SUCURSALES
    FOREIGN KEY (SUCURSAL_ID) REFERENCES SUCURSALES (ID)
);

-- TABLA VENTAS
CREATE TABLE VENTAS (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    SUCURSAL_ID INT NOT NULL,
    PAGO_ID INT NOT NULL,
    CLIENTE_ID INT NOT NULL,
    COMENTARIO VARCHAR(500),
    USUARIO_ID INT NOT NULL,
    MONEDA_ID INT NOT NULL,
    DOCUMENTO_ID INT NOT NULL,
    FECHA_CREACION DATETIME DEFAULT GETDATE(),
    ESTADO BIT DEFAULT 1,
    CONSTRAINT FK_VENTAS_SUCURSALES
    FOREIGN KEY (SUCURSAL_ID) REFERENCES SUCURSALES (ID),
    CONSTRAINT FK_VENTAS_PAGOS
    FOREIGN KEY (PAGO_ID) REFERENCES PAGOS (ID),
    CONSTRAINT FK_VENTAS_CLIENTES
    FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTES (ID),
    CONSTRAINT FK_VENTAS_USUARIOS
    FOREIGN KEY (USUARIO_ID) REFERENCES USUARIOS (ID),
    CONSTRAINT FK_VENTAS_MONEDAS
    FOREIGN KEY (MONEDA_ID) REFERENCES MONEDAS (ID),
    CONSTRAINT FK_VENTAS_DOCUMENTOS
    FOREIGN KEY (DOCUMENTO_ID) REFERENCES DOCUMENTOS (ID)
);

-- TABLA VENTADETALLES
CREATE TABLE VENTADETALLES (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    VENTA_ID INT NOT NULL,
    PRODUCTO_ID INT NOT NULL,
    PRODUCTO_PRECIO_VENTA NUMERIC(18, 2) NOT NULL,
    CANTIDAD INT NOT NULL,
    FECHA_CREACION DATETIME DEFAULT GETDATE(),
    ESTADO BIT DEFAULT 1,
    CONSTRAINT FK_VENTADETALLES_VENTAS
    FOREIGN KEY (VENTA_ID) REFERENCES VENTAS (ID),
    FOREIGN KEY (PRODUCTO_ID) REFERENCES PRODUCTOS (ID)
);

-- TABLA UNIDADES
CREATE TABLE UNIDADES (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    SUCURSAL_ID INT NOT NULL,
    NOMBRE VARCHAR(150) NOT NULL,
    FECHA_CREACION DATETIME DEFAULT GETDATE(),
    ESTADO BIT DEFAULT 1,
    FOREIGN KEY (SUCURSAL_ID) REFERENCES Sucursales (ID)
);

-- LISTA USUARIOS POR SUCURSAL
CREATE PROCEDURE [dbo].[SP_L_USUARIO_BY_SUCURSAL]    
@SUCURSAL_ID INT    
AS    
BEGIN    
SELECT          
USUARIOS.ID,   
USUARIOS.SUCURSAL_ID,   
USUARIOS.CORREO,   
USUARIOS.NOMBRE,   
USUARIOS.APELLIDO,   
USUARIOS.DNI,   
USUARIOS.TELEFONO,   
USUARIOS.CONTRASENIA,  
USUARIOS.IMAGEN, 
USUARIOS.ROL_ID,   
USUARIOS.FECHA_CREACION,  
ROLES.NOMBRE AS ROL_NOMBRE,   
USUARIOS.ESTADO  
FROM              
USUARIOS INNER JOIN  
ROLES ON USUARIOS.ROL_ID = ROLES.ROL_ID  
WHERE    
USUARIOS.SUCURSAL_ID = @SUCURSAL_ID    
AND USUARIOS.ESTADO=1    
END
GO

-- LISTA USUARIO POR ID
CREATE PROCEDURE [dbo].[SP_L_USUARIO_BY_ID]
@ID INT
AS
BEGIN
	SELECT * FROM USUARIOS
	WHERE
	ID = @ID
END
GO

-- DESACTIVA UN USUARIO
CREATE PROCEDURE [dbo].[SP_D_USUARIO]
@ID INT
AS
BEGIN
	UPDATE USUARIOS
	SET
		ESTADO = 0
	WHERE
		ID = @ID
END
GO

-- INSERTA UN USUARIO
CREATE PROCEDURE [dbo].[SP_I_USUARIO]  
@SUCURSAL_ID INT,  
@CORREO VARCHAR(150),  
@NOMBRE VARCHAR(150),  
@APELLIDO VARCHAR(150),  
@DNI VARCHAR(150),  
@TELEFONO VARCHAR(150),  
@CONTRASENIA VARCHAR(150),  
@ROL_ID INT,
@IMAGEN VARCHAR(MAX)
AS  
BEGIN  
 INSERT INTO USUARIOS  
 (SUCURSAL_ID,CORREO,NOMBRE,APELLIDO,DNI,TELEFONO,CONTRASENIA,ROL_ID,IMAGEN,FECHA_CREACION,ESTADO)  
 VALUES  
 (@SUCURSAL_ID,@CORREO,@NOMBRE,@APELLIDO,@DNI,@TELEFONO,@CONTRASENIA,@ROL_ID,@IMAGEN,GETDATE(),1)  
END  
GO

-- ACTUALIZA UN USUARIO
CREATE PROCEDURE [dbo].[SP_U_USUARIO]  
@ID INT,  
@SUCURSAL_ID INT,  
@CORREO VARCHAR(150),  
@NOMBRE VARCHAR(150),  
@APELLIDO VARCHAR(150),  
@DNI VARCHAR(150),  
@TELEFONO VARCHAR(150),  
@CONTRASENIA VARCHAR(150),  
@ROL_ID INT,
@IMAGEN VARCHAR(MAX)
AS  
BEGIN  
 UPDATE USUARIOS  
 SET  
  SUCURSAL_ID = @SUCURSAL_ID,  
  CORREO = @CORREO,  
  NOMBRE = @NOMBRE,  
  APELLIDO = @APELLIDO,  
  DNI = @DNI,  
  TELEFONO = @TELEFONO,  
  CONTRASENIA = @CONTRASENIA,  
  ROL_ID = @ROL_ID,
  IMAGEN = @IMAGEN
 WHERE  
  ID = @ID  
END
GO

-- ACTUALIZA CONTRASENIA DE USUARIO
CREATE PROCEDURE [dbo].[SP_U_USUARIO_CONTRASENIA]
@ID INT,
@CONTRASENIA VARCHAR(50)
AS
BEGIN
	UPDATE USUARIOS
	SET
		CONTRASENIA = @CONTRASENIA
	WHERE
		ID = @ID
END
GO

-- LOGIN DE USUARIO
CREATE PROCEDURE [dbo].[SP_L_USUARIO_LOGIN]    
@SUCURSAL_ID INT,    
@CORREO VARCHAR(50),    
@CONTRASENIA VARCHAR(30)    
AS    
BEGIN    
 SELECT            
 USUARIOS.ID,     
 USUARIOS.SUCURSAL_ID,     
 USUARIOS.CORREO,     
 USUARIOS.NOMBRE,     
 USUARIOS.APELLIDO,     
 USUARIOS.DNI,     
 USUARIOS.TELEFONO,     
 USUARIOS.CONTRASENIA,     
 USUARIOS.ROL_ID,    
 USUARIOS.IMAGEN, 
 SUCURSALES.NOMBRE AS SUCURSAL_NOMBRE
 FROM      
 USUARIOS INNER JOIN    
 SUCURSALES ON USUARIOS.SUCURSAL_ID = SUCURSALES.ID  
 WHERE    
 USUARIOS.SUCURSAL_ID = @SUCURSAL_ID     
 AND USUARIOS.CORREO = @CORREO    
 AND USUARIOS.CONTRASENIA = @CONTRASENIA    
 AND USUARIOS.ESTADO = 1    
END
GO

-- CUENTA USUARIOS POR SUCURSAL
CREATE PROCEDURE SP_CANTIDAD_USUARIO_X_SUC @SUCURSAL_ID INT
AS
BEGIN
SELECT COUNT(*) AS 'Cantidad Usuario' FROM USUARIOS WHERE SUCURSAL_ID =  @SUCURSAL_ID AND ESTADO=1;
END
GO

-- LISTA MENU POR ROL
CREATE PROCEDURE [dbo].[SP_L_MENU_BY_ROL_ID]
@ROL_ID INT
AS
BEGIN
	SELECT        
	MENUDETALLES.ID, 
	MENUDETALLES.MENU_ID, 
	MENUDETALLES.ROL_ID, 
	MENUDETALLES.PERMITIDO, 
	MENUDETALLES.FECHA_CREACION, 
	MENUDETALLES.ESTADO, 
	MENUS.NOMBRE, 
	MENUS.RUTA, 
	MENUS.IDENTIFICADOR,
	MENUS.GRUPO,
	MENUS.ICONO
	FROM            
	MENUDETALLES INNER JOIN
	MENUS ON MENUDETALLES.MENU_ID = MENUS.ID
	WHERE 
	MENUDETALLES.ROL_ID = @ROL_ID
END
GO

-- INSERTA MENU POR ROL
CREATE PROCEDURE [dbo].[SP_I_MENU_BY_ROL_ID]
@ROL_ID INT
AS
BEGIN
	IF (SELECT COUNT(*) FROM MENUDETALLES WHERE ROL_ID=@ROL_ID)=0
	BEGIN
		INSERT INTO MENUDETALLES
		(MENU_ID,ROL_ID,PERMITIDO,FECHA_CREACION,ESTADO)
		(SELECT ID,@ROL_ID,0,GETDATE(),1 FROM MENUS WHERE ESTADO=1)
	END
	ELSE
	BEGIN
		INSERT INTO MENUDETALLES
		(MENU_ID,ROL_ID,PERMITIDO,FECHA_CREACION,ESTADO)
		(SELECT ID,@ROL_ID,0,GETDATE(),1 FROM MENUS WHERE ESTADO=1 AND ID NOT IN (SELECT MENU_ID FROM MENUDETALLES WHERE ROL_ID=@ROL_ID))
	END
END
GO

-- HABILITA MENU
CREATE PROCEDURE [dbo].[SP_U_MENU_HABILITAR]
@ID INT
AS
BEGIN
	UPDATE MENUDETALLES
	SET
		PERMITIDO = 1
	WHERE
		ID = @ID
END
GO

-- DESHABILITA MENU
CREATE PROCEDURE [dbo].[SP_U_MENU_DESHABILITAR]
@ID INT
AS
BEGIN
	UPDATE MENUDETALLES
	SET
		PERMITIDO = 0
	WHERE
		ID = @ID
END
GO

-- LISTA ROLES POR SUCURSAL
CREATE PROCEDURE [dbo].[SP_L_ROL_BY_SUCURSAL]
@SUCURSAL_ID INT
AS
BEGIN
	SELECT * FROM ROLES
	WHERE
	SUCURSAL_ID = @SUCURSAL_ID
	AND ESTADO=1
END
GO

-- LISTA ROL POR ID
CREATE PROCEDURE [dbo].[SP_L_ROL_BY_ID]
@ROL_ID INT
AS
BEGIN
	SELECT * FROM ROLES
	WHERE
	ROL_ID = @ROL_ID
END
GO

-- DESACTIVA UN ROL
CREATE PROCEDURE [dbo].[SP_D_ROL]
@ROL_ID INT
AS
BEGIN
	UPDATE ROLES
	SET
		ESTADO = 0
	WHERE
		ROL_ID = @ROL_ID
END
GO

-- INSERTA UN ROL
CREATE PROCEDURE [dbo].[SP_I_ROL]
@SUCURSAL_ID INT,
@NOMBRE VARCHAR(150)
AS
BEGIN
	INSERT INTO ROLES
	(SUCURSAL_ID,NOMBRE,FECHA_CREACION,ESTADO)
	VALUES
	(@SUCURSAL_ID,@NOMBRE,GETDATE(),1)
END
GO

-- ACTUALIZA UN ROL
CREATE PROCEDURE [dbo].[SP_U_ROL]
@ROL_ID INT,
@SUCURSAL_ID INT,
@NOMBRE VARCHAR(150)
AS
BEGIN
	UPDATE ROLES
	SET
		SUCURSAL_ID = @SUCURSAL_ID,
		NOMBRE = @NOMBRE
	WHERE
		ROL_ID = @ROL_ID
END
GO

-- VALIDA ACCESO AL MENU
CREATE PROCEDURE [dbo].[SP_L_MENU_VALIDAR_ACCESO]
@USUARIO_ID INT,
@IDENTIFICADOR VARCHAR(100)
AS  
BEGIN  
	SELECT        
	MENUDETALLES.ID, 
	MENUDETALLES.MENU_ID, 
	MENUDETALLES.ROL_ID, 
	MENUDETALLES.PERMITIDO, 
	MENUDETALLES.FECHA_CREACION, 
	MENUDETALLES.ESTADO, 
	MENUS.NOMBRE, 
	MENUS.RUTA, 
	MENUS.IDENTIFICADOR, 
	MENUS.GRUPO, 
	USUARIOS.ID AS USUARIO_ID, 
	ROLES.NOMBRE AS ROL_NOMBRE
	FROM            
	MENUDETALLES INNER JOIN
	MENUS ON MENUDETALLES.MENU_ID = MENUS.ID INNER JOIN
	ROLES ON MENUDETALLES.ROL_ID = ROLES.ROL_ID INNER JOIN
	USUARIOS ON ROLES.ROL_ID = USUARIOS.ROL_ID
 WHERE   
	USUARIOS.ID = @USUARIO_ID  
	AND PERMITIDO = 1
	AND MENUS.IDENTIFICADOR = @IDENTIFICADOR
END
GO

-- LISTA SUCURSALES
CREATE PROCEDURE [dbo].[SP_L_SUCURSALES]
AS
BEGIN
	SELECT * FROM SUCURSALES
	WHERE ESTADO=1
END
GO

-- LISTA SUCURSAL POR ID
CREATE PROCEDURE [dbo].[SP_L_SUCURSAL_BY_ID]
@ID INT
AS
BEGIN
	SELECT * FROM SUCURSALES
	WHERE
	ID = @ID
END
GO

-- DESACTIVA UNA SUCURSAL
CREATE PROCEDURE [dbo].[SP_D_SUCURSAL]
@ID INT
AS
BEGIN
	UPDATE SUCURSALES
	SET
		ESTADO = 0
	WHERE
		ID = @ID
END
GO

-- INSERTA UNA SUCURSAL
CREATE PROCEDURE [dbo].[SP_I_SUCURSAL]
@NOMBRE VARCHAR(150)
AS
BEGIN
	INSERT INTO SUCURSALES
	(NOMBRE,FECHA_CREACION,ESTADO)
	VALUES
	(@NOMBRE,GETDATE(),1)
END
GO

-- ACTUALIZA UNA SUCURSAL
CREATE PROCEDURE [dbo].[SP_U_SUCURSAL]
@ID INT,
@NOMBRE VARCHAR(150)
AS
BEGIN
	UPDATE SUCURSALES
	SET
		NOMBRE = @NOMBRE
	WHERE
		ID = @ID
END
GO


-- LISTA PRODUCTOS POR SUCURSAL
CREATE PROCEDURE [dbo].[SP_L_PRODUCTO_BY_SUCURSAL_ID]  
@SUCURSAL_ID INT  
AS  
BEGIN  
SELECT        
PRODUCTOS.ID, 
PRODUCTOS.SUCURSAL_ID, 
PRODUCTOS.CATEGORIA_ID, 
PRODUCTOS.NOMBRE, 
PRODUCTOS.DESCRIPCION, 
PRODUCTOS.STOCK,
PRODUCTOS.PROVEEDOR_ID,
PROVEEDORES.NOMBRE AS PROVEEDOR_NOMBRE,
PRODUCTOS.MONEDA_ID,  
PRODUCTOS.PRECIO_VENTA, 
PRODUCTOS.PRODUCTO_IMG, 
PRODUCTOS.FECHA_CREACION, 
PRODUCTOS.ESTADO, 
CATEGORIAS.NOMBRE AS CATEGORIA_NOMBRE, 
MONEDAS.CODIGO_ISO,
MONEDAS.SIMBOLO
FROM            
PRODUCTOS INNER JOIN
CATEGORIAS ON PRODUCTOS.CATEGORIA_ID = CATEGORIAS.ID INNER JOIN
MONEDAS ON PRODUCTOS.MONEDA_ID = MONEDAS.ID
INNER JOIN PROVEEDORES ON PROVEEDORES.ID = PRODUCTOS.PROVEEDOR_ID
 WHERE  
 PRODUCTOS.SUCURSAL_ID = @SUCURSAL_ID  
 AND PRODUCTOS.ESTADO=1  
END  
GO

-- CUENTA PRODUCTOS POR SUCURSAL
CREATE PROCEDURE SP_CANTIDAD_PRODUCTO_BY_SUCURSAL_ID @SUCURSAL_ID INT
AS
BEGIN
SELECT COUNT(*) AS 'Cantidad Producto' FROM PRODUCTOS WHERE SUCURSAL_ID =  @SUCURSAL_ID AND ESTADO=1;
END
GO

-- LISTA PRODUCTO POR ID
CREATE PROCEDURE [dbo].[SP_L_PRODUCTO_BY_ID]  
@ID INT  
AS  
BEGIN  
 SELECT          
PRODUCTOS.ID,   
PRODUCTOS.SUCURSAL_ID,   
PRODUCTOS.CATEGORIA_ID,   
PRODUCTOS.NOMBRE,   
PRODUCTOS.DESCRIPCION, 
PRODUCTOS.MONEDA_ID,   
PROVEEDORES.ID AS PROVEEDOR_ID,
PRODUCTOS.PRECIO_VENTA,   
PRODUCTOS.STOCK,   
PRODUCTOS.PRODUCTO_IMG,   
PRODUCTOS.FECHA_CREACION,   
PRODUCTOS.ESTADO,   
CATEGORIAS.NOMBRE AS CATEGORIA_NOMBRE,   
MONEDAS.NOMBRE AS MONEDA_NOMBRE
FROM              
PRODUCTOS INNER JOIN  
CATEGORIAS ON PRODUCTOS.CATEGORIA_ID = CATEGORIAS.ID INNER JOIN  
MONEDAS ON PRODUCTOS.MONEDA_ID = MONEDAS.ID INNER JOIN PROVEEDORES ON
PROVEEDORES.ID = PRODUCTOS.PROVEEDOR_ID
 WHERE  
 PRODUCTOS.ID = @ID  
END
GO

-- LISTA PRODUCTOS POR CATEGORIA
CREATE PROCEDURE [dbo].[SP_L_PRODUCTO_BY_CATEGORIA_ID]    
@CATEGORIA_ID INT    
AS    
BEGIN    
SELECT          
PRODUCTOS.ID,   
PRODUCTOS.SUCURSAL_ID,   
PRODUCTOS.CATEGORIA_ID,   
PRODUCTOS.NOMBRE,   
PRODUCTOS.DESCRIPCION, 
PRODUCTOS.MONEDA_ID,    
PRODUCTOS.PRECIO_VENTA,   
PRODUCTOS.STOCK,   
PRODUCTOS.PRODUCTO_IMG,   
PRODUCTOS.FECHA_CREACION,   
PRODUCTOS.ESTADO,   
CATEGORIAS.NOMBRE AS CATEGORIA_NOMBRE,   
MONEDAS.NOMBRE AS MONEDA_NOMBRE
FROM              
PRODUCTOS INNER JOIN  
CATEGORIAS ON PRODUCTOS.CATEGORIA_ID = CATEGORIAS.ID INNER JOIN  
MONEDAS ON PRODUCTOS.MONEDA_ID = MONEDAS.ID
 WHERE    
 PRODUCTOS.CATEGORIA_ID = @CATEGORIA_ID    
 AND PRODUCTOS.ESTADO=1    
END 
GO

-- DESACTIVA UN PRODUCTO
CREATE PROCEDURE [dbo].[SP_D_PRODUCTO]
@ID INT
AS
BEGIN
	UPDATE PRODUCTOS
	SET
		ESTADO = 0
	WHERE
		ID = @ID
END
GO

-- INSERTA UN PRODUCTO
CREATE PROCEDURE [dbo].[SP_I_PRODUCTO]
@SUCURSAL_ID INT,
@CATEGORIA_ID INT,
@NOMBRE VARCHAR(150),
@DESCRIPCION VARCHAR(150),
@MONEDA_ID INT,
@PRECIO_VENTA NUMERIC(18,2),
@PROVEEDOR_ID INT,
@PRODUCTO_IMG VARCHAR(MAX)
AS
BEGIN
	INSERT INTO PRODUCTOS
	(SUCURSAL_ID,CATEGORIA_ID,NOMBRE,DESCRIPCION,STOCK,PROVEEDOR_ID,MONEDA_ID,PRECIO_VENTA,PRODUCTO_IMG,FECHA_CREACION,ESTADO)
	VALUES
	(@SUCURSAL_ID,@CATEGORIA_ID,@NOMBRE,@DESCRIPCION,0,@PROVEEDOR_ID,@MONEDA_ID,@PRECIO_VENTA,@PRODUCTO_IMG,GETDATE(),1)
END
GO

-- ACTUALIZA UN PRODUCTO
CREATE PROCEDURE [dbo].[SP_U_PRODUCTO]
@ID INT,
@SUCURSAL_ID INT,
@CATEGORIA_ID INT,
@NOMBRE VARCHAR(150),
@DESCRIPCION VARCHAR(150),
@PROVEEDOR_ID INT,
@MONEDA_ID INT,
@PRECIO_VENTA NUMERIC(18,2),
@PRODUCTO_IMG VARCHAR(MAX)
AS
BEGIN
	UPDATE PRODUCTOS
	SET
		SUCURSAL_ID = @SUCURSAL_ID,
		CATEGORIA_ID = @CATEGORIA_ID,
		NOMBRE = @NOMBRE,
		DESCRIPCION = @DESCRIPCION,
		PROVEEDOR_ID = @PROVEEDOR_ID,
		MONEDA_ID = @MONEDA_ID,
		PRECIO_VENTA = @PRECIO_VENTA,
		PRODUCTO_IMG = @PRODUCTO_IMG
	WHERE
		ID = @ID
END
GO

-- LISTA MOVIMIENTOS DE PRODUCTO (COMPRAS Y VENTAS)
CREATE PROCEDURE [dbo].[SP_L_PRODUCTO_]
@ID INT
AS
BEGIN
	SELECT * FROM 
	(
		SELECT        
		COMPRAS.ID AS COMPRA_ID, 
		CONVERT(VARCHAR,COMPRAS.FECHA_CREACION,103) AS FECHA_CREACION,
		COMPRADETALLES.CANTIDAD, 
		COMPRADETALLES.PRODUCTO_ID, 
		DOCUMENTOS.NOMBRE AS DOCUMENTO_NOMBRE,
		'Compra' AS REGISTRO
		FROM            
		COMPRAS INNER JOIN
		COMPRADETALLES ON COMPRAS.ID = COMPRADETALLES.COMPRA_ID INNER JOIN
		DOCUMENTOS ON COMPRAS.DOCUMENTO_ID = DOCUMENTOS.ID
		WHERE        
		COMPRAS.ESTADO = 1 
		AND COMPRADETALLES.PRODUCTO_ID = @ID

		UNION ALL

		SELECT        
		VENTAS.ID AS VENTA_ID, 
		CONVERT(VARCHAR,VENTAS.FECHA_CREACION,103) AS FECHA_CREACION,
		VENTADETALLES.CANTIDAD, 
		VENTADETALLES.PRODUCTO_ID, 
		DOCUMENTOS.NOMBRE AS DOCUMENTO_NOMBRE,
		'Venta' AS REGISTRO
		FROM            
		VENTAS INNER JOIN
		VENTADETALLES ON VENTAS.ID = VENTADETALLES.VENTA_ID INNER JOIN
		DOCUMENTOS ON VENTAS.DOCUMENTO_ID = DOCUMENTOS.ID
		WHERE        
		VENTAS.ESTADO = 1 
		AND VENTADETALLES.PRODUCTO_ID = @ID
	) TABLA 
	ORDER BY 
	FECHA_CREACION DESC
END
GO

-- LISTA INFO DE PRODUCTO CON CATEGORIA
CREATE PROCEDURE SP_L_PRODUCTO_INFO
@ID INT 
AS 
BEGIN 
	SELECT * FROM PRODUCTOS P INNER JOIN CATEGORIAS C ON P.CATEGORIA_ID = C.ID WHERE P.ID = @ID; 
END
GO
